package in.fortytwo42.adapter.service;

public interface ErrorConstantsFromConfigIntf {
    public Long getERROR_CODE_APPLICATION_NOT_FOUND();

    public Long getERROR_CODE_APPLICATION_ALREADY_PRESENT();

    public long getERROR_CODE_USER_UPDATE_PENDING();

    public long getERROR_CODE_INVALID_TOKEN();

    public long getERROR_CODE_INVALID_ROLES();

    public long getERROR_CODE_PERMISSION_DENIED();

    public long getERROR_CODE_IO_EXCEPTION();

    public long getERROR_CODE_INVALID_APPLICATION_ID_OR_PASSWORD();

    public long getERROR_CODE_USER_SERVICE_BINDING_FAILED();

    public long getERROR_CODE_INVALID_MOBILE();

    public long getERROR_CODE_INVALID_APPLICATION_FOR_USER();

    public long getERROR_CODE_CERTIFICATE_PINNING_FAILURE();

    public long getERROR_CODE_SERVER_ERROR();

    public long getERROR_CODE_ACCOUNT_NOT_FOUND();

    public long getERROR_CODE_IAMCI2_CALL_FAILED();

    public long getERROR_CODE_LOOKUP_ID_COMPULSORY();

    public long getERROR_CODE_APPROVAL_ATTEMPT_TYPE_INVALID();

    public long getERROR_CODE_INVALID_CONSUMER_ID();

    public long getERROR_CODE_APPROVAL_ATTEMPT_NOT_APPROVED();

    public long getERROR_CODE_INVALID_APPLICATION_ID();

    public long getERROR_CODE_INVALID_CLIENT_ID();

    public long getERROR_CODE_INVALID_DATA();

    public long getERROR_CODE_USER_BLOCK();

    public long getERROR_CODE_CONSUMER_NOT_PRESENT_DATA();

    public long getERROR_CODE_SERVICE_NOT_FOUND();

    public long getERROR_CODE_INVALID_SERVICE_FOR_APPLICATION();

    public long getERROR_CODE_USER_SERVICE_BINDING_ALREADY_PRESENT();

    public long getERROR_CODE_USER_SERVICE_BINDING_NOT_FOUND();

    public long getERROR_CODE_USER_NOT_FOUND();

    public long getERROR_CODE_TRANSACTION_NOT_FOUND();

    public long getERROR_CODE_INVALID_TRANSACTION_TYPE();

    public long getERROR_CODE_VERIFICATION_FAILED();

    public long getERROR_CODE_USER_NAME_PASSWORD_INVALID();
    public long getERROR_CODE_USER_NAME_TOKEN_INVALID();

    public long getERROR_CODE_INVALID_APPLICATION_TYPE();

    public long getERROR_CODE_BLOCKED_FOR_RESET_PIN();

    public long getERROR_CODE_RESET_PIN_COMPLETED();

    public long getERROR_CODE_USER_SERVICE_BINDING_NOT_ACTIVE();

    public long getERROR_CODE_USER_SERVICE_ALREADY_PRESENT();

    public long getERROR_CODE_USER_SERVICE_NOT_FOUND();

    public long getERROR_CODE_USER_DATA_EMPTY();

    public long getERROR_CODE_REQUEST_NOT_FOUND();

    public long getERROR_CODE_INVALID_APPLICATION_NAME();

    public long getERROR_CODE_USER_SERVICE_BINDING_BLOCKED();

    public long getERROR_CODE_APPLICATION_PASSWORD();

    public long getERROR_CODE_SERVICES_ALREADY_ENABLED_FOR_USER();

    public long getERROR_CODE_USER_APPLICATION_BINDING_NOT_FOUND();

    public long getERROR_CODE_ATTRIBUTE_NOT_FOUND();

    public long getERROR_CODE_EVIDENCE_NOT_FOUND();

    public long getERROR_CODE_PENDING_AUTHENTICATION_ATTEMPT_NOT_FOUND();

    public long getERROR_CODE_ATTRIBUTE_ADDITION_ALREADY_PRESENT();

    public long getERROR_CODE_INVALID_REQUEST();

    public long getERROR_CODE_ATTRIBUTE_ALREADY_PRESENT();

    public long getERROR_CODE_ALREADY_APPROVED();

    public long getERROR_CODE_ATTRIBUTE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_REQUEST_IS_TIMEOUT();

    public long getERROR_CODE_ATTRIBUTE_UPDATION_ALREADY_PRESENT();

    public long getERROR_CODE_ATTRIBUTE_DELETION_ALREADY_PRESENT();

    public long getERROR_CODE_EXISTING_AND_UPDATED_DATA_IS_SAME();

    public long getERROR_CODE_ATTRIBUTE_MASTER_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_REQUEST_ALREADY_SENT_TO_CHECKER();

    public long getERROR_CODE_EVIDENCE_REQUEST_ALREADY_SENT_TO_USER();

    public long getERROR_CODE_ATTRIBUTE_ADDITION_ID_INVALID();

    public long getERROR_CODE_INVALID_ATTRIBUTE_TYPE();

    public long getERROR_CODE_INVALID_ATTRIBUTE_NAME();

    public long getERROR_CODE_FILE_IS_EMPTY();

    public long getERROR_CODE_FILE_NOT_SUPPORTED();

    public long getERROR_CODE_APPLICATION_ONBOARD_ALREADY_PRESENT();

    public long getERROR_CODE_EDIT_ACCOUNT_FAILED();

    public long getERROR_CODE_ATTRIBUTE_VALUE_IS_INVALIDE();

    public long getERROR_CODE_EVIDENCE_REQUEST_ALREADY_REJECTED();

    public long getERROR_CODE_APPLICATION_EDIT_ALREADY_PRESENT();

    public long getERROR_CODE_USER_ONBOARD_ALREADY_PRESENT();

    public long getERROR_CODE_CSV_DOWNLOAD_FAILED();

    public long getERROR_CODE_USER_SESSION_IS_ALREADY_ACTIVE();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_REQUEST_DATA_NOT_FOUND();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_ONBOARD_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_UPDATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_DELETE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_NOT_FOUND();

    public long getERROR_CODE_SRA_APPLICATION_GATEWAY_SETTING_REL_NOT_FOUND();

    public long getERROR_CODE_SRA_APPLICATION_GATEWAY_SETTING_NOT_FOUND();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_DATA_ALREADY_PRESENT();

    public long getERROR_CODE_ENTERPRISE_NOT_FOUND();

    public long getERROR_CODE_SRA_GATEWAY_SETTING_ALREADY_BINDED();

    public long getERROR_CODE_POLICY_ONBOARD_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_POLICY_EDIT_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_DEVICE_EDIT_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_TOKEN_EDIT_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_USER_SERVICE_BIND_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_USER_SERVICE_UNBIND_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_USER_GROUP_ALREADY_EXISTS();

    public long getERROR_CODE_USER_GROUP_NOT_FOUND();

    public long getERROR_CODE_USER_GROUP_DATA_SAME();

    public long getERROR_CODE_USER_GROUP_CREATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_USER_GROUP_BINDING_ALREADY_EXISTS();

    public long getERROR_CODE_USER_GROUP_BINDING_NOT_FOUND();

    public long getERROR_CODE_USER_GROUP_APPLICATION_BINDING_ALREADY_EXISTS();

    public long getERROR_CODE_USER_GROUP_APPLICATION_BINDING_NOT_FOUND();

    public long getERROR_CODE_IDENTITY_PROVIDER_CREATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_APPLICATION_ALREDY_BINDED();

    public long getERROR_CODE_USER_GROUP_UPDATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_USER_USER_GROUP_MAPPING_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_APPLICATION_USER_GROUP_MAPPING_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_CONTACT_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_CONTACT_EDIT_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_MAPPER_CREATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_MAPPER_NOT_FOUND();

    public long getERROR_CODE_AD_SYNC_FAILED();

    public long getERROR_CODE_SRA_DETAILS_NOT_MATCHED();

    public long getERROR_CODE_INVALID_FILE_NAME();

    public long getERROR_CODE_FILE_READ_FAILED();

    public long getERROR_CODE_LICENSE_CHECK_FAILED();

    public long getERROR_CODE_INPROGRESS();

    public long getERROR_CODE_ENTERPRISE_ALREADY_ONBOARDED();

    public long getERROR_CODE_ENTERPRISE_NOT_ONBOARDED();

    public long getERROR_CODE_BINDING_FAILED();

    public long getERROR_CODE_NOTIFICATION_TYPE_NOT_FOUND();

    public long getERROR_CODE_TWO_FACTOR_AUTH_DISABLED_FOR_USER();

    public long getERROR_CODE_TWO_FACTOR_AUTH_DISABLED_FOR_APPLICATION();

    public long getERROR_CODE_INVALID_CONNECTION_SETTINGS();

    public long getERROR_CODE_ADFS_DETAIL_NOT_FOUND();

    public long getERROR_CODE_AD_DETAIL_NOT_FOUND();

    public long getERROR_CODE_SAME_MAKER_REQUEST_APPROVED();

    public long getERROR_CODE_INVALID_USERID_PASSWORD();

    public long getERROR_CODE_USER_CREDENTIALS_NOT_PRESENT();

    public long getERROR_CODE_EVIDENCE_IS_REQUIRED();

    public long getERROR_CODE_INVALID_TYPE();

    public long getERROR_CODE_APPLICATION_NOT_ACTIVE();

    public long getERROR_CODE_PARSING_CSV();

    public long getERROR_CODE_REQUEST_NOT_PENDING();

    public long getERROR_CODE_ATTRIBUTE_MASTER_ADDITION_ALREADY_PRESENT();

    public long getERROR_CODE_ATTRIBUTE_META_DATA_NOT_FOUND();

    public long getERROR_CODE_VERIFIER_NOT_FOUND();

    public long getERROR_CODE_EVIDENCE_REQUEST_ALREADY_APPROVED();

    public long getERROR_CODE_USER_GROUP_DELETE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_ATTRIBUTE_NOT_PRESENT();

    public long getALREADY_PRESENT_IN_SYSTEM_CODE();

    public long getVALIDATION_ERROR_CODE();

    public long getUSER_NOT_FOUND();

    public long getERROR_CODE_INTERNAL_SERVER_ERROR();

    public long getERROR_CODE_STATE_MACHINE_WORKFLOW_ONBOARD_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_STATE_MACHINE_WORKFLOW_UPDATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_ACCOUNT_CUSTOM_STATE_MACHINE_ONBOARD_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_ACCOUNT_CUSTOM_STATE_MACHINE_UPDATE_REQUEST_ALREADY_PRESENT();

    public long getERROR_CODE_INVALID_ACCOUNT_ID();

    public long getERROR_CODE_GENERATE_RUNNING_HASH_FAILED();
    public long getERROR_CODE_VERIFY_RUNNING_HASH_FAILED();
    public String getERROR_MESSAGE_INVALID_DATA();

    public String getERROR_MESSAGE_TRANSACTION_ALREADY_EXISTS();

    public String getERROR_MESSAGE_USER_BLOCK();

    public String getERROR_MESSAGE_CONSUMER_NOT_PRESENT_DATA();

    public String getERROR_MESSAGE_SERVICE_NOT_FOUND();

    public String getERROR_MESSAGE_INVALID_SERVICE_FOR_APPLICATION();

    public String getERROR_MESSAGE_USER_SERVICE_BINDING_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_SERVICE_BINDING_NOT_FOUND();

    public String getERROR_MESSAGE_USER_NOT_FOUND();

    public String getERROR_MESSAGE_TRANSACTION_NOT_FOUND();

    public String getERROR_MESSAGE_INVALID_TRANSACTION_TYPE();

    public String getERROR_MESSAGE_VERIFICATION_FAILED();

    public String getERROR_MESSAGE_USER_NAME_PASSWORD_INVALID();

    public String getERROR_MESSAGE_INVALID_APPLICATION_TYPE();

    public String getERROR_MESSAGE_BLOCKED_FOR_RESET_PIN();

    public String getERROR_MESSAGE_RESET_PIN_COMPLETED();

    public String getERROR_MESSAGE_USER_SERVICE_BINDING_NOT_ACTIVE();

    public String getERROR_MESSAGE_USER_SERVICE_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_SERVICE_NOT_FOUND();

    public String getERROR_MESSAGE_USER_DATA_EMPTY();

    public String getERROR_MESSAGE_REQUEST_NOT_FOUND();

    public String getERROR_MESSAGE_INVALID_APPLICATION_NAME();

    public String getERROR_MESSAGE_USER_SERVICE_BINDING_BLOCKED();

    public String getERROR_MESSAGE_APPLICATION_PASSWORD();

    public String getERROR_MESSAGE_SERVICES_ALREADY_ENABLED_FOR_USER();

    public String getERROR_MESSAGE_USER_APPLICATION_BINDING_NOT_FOUND();

    public String getERROR_MESSAGE_ATTRIBUTE_NOT_FOUND();

    public String getERROR_MESSAGE_EVIDENCE_NOT_FOUND();

    public String getERROR_MESSAGE_PENDING_AUTHENTICATION_ATTEMPT_NOT_FOUND();

    public String getERROR_MESSAGE_ATTRIBUTE_ADDITION_ALREADY_PRESENT();

    public String getERROR_MESSAGE_INVALID_REQUEST();

    public String getERROR_MESSAGE_ATTRIBUTE_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ATTRIBUTE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_REQUEST_IS_TIMEOUT();

    public String getERROR_MESSAGE_ATTRIBUTE_UPDATION_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ATTRIBUTE_DELETION_ALREADY_PRESENT();

    public String getERROR_MESSAGE_EXISTING_AND_UPDATED_DATA_IS_SAME();

    public String getERROR_MESSAGE_ATTRIBUTE_MASTER_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_REQUEST_ALREADY_SENT_TO_CHECKER();

    public String getERROR_MESSAGE_EVIDENCE_REQUEST_ALREADY_SENT_TO_USER();

    public String getERROR_MESSAGE_ATTRIBUTE_ADDITION_ID_INVALID();

    public String getERROR_MESSAGE_INVALID_ATTRIBUTE_TYPE();

    public String getERROR_MESSAGE_INVALID_ATTRIBUTE_NAME();

    public String getERROR_MESSAGE_FILE_IS_EMPTY();

    public String getERROR_MESSAGE_APPLICATION_ONBOARD_ALREADY_PRESENT();

    public String getERROR_MESSAGE_EDIT_ACCOUNT_FAILED();

    public String getERROR_MESSAGE_ATTRIBUTE_VALUE_IS_INVALIDE();

    public String getERROR_MESSAGE_EVIDENCE_REQUEST_ALREADY_REJECTED();

    public String getERROR_MESSAGE_APPLICATION_EDIT_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_ONBOARD_ALREADY_PRESENT();

    public String getERROR_DEVELOPER_CSV_DOWNLOAD_FAILED();

    public String getERROR_MESSAGE_USER_SESSION_IS_ALREADY_ACTIVE();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_REQUEST_DATA_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_ONBOARD_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_UPDATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_DELETE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_APPLICATION_GATEWAY_SETTING_REL_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_APPLICATION_GATEWAY_SETTING_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_DATA_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ENTERPRISE_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_GATEWAY_SETTING_ALREADY_BINDED();

    public String getERROR_MESSAGE_POLICY_ONBOARD_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_POLICY_EDIT_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_DEVICE_EDIT_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_TOKEN_EDIT_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_SERVICE_BIND_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_SERVICE_UNBIND_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_GROUP_NOT_FOUND();

    public String getERROR_MESSAGE_USER_GROUP_DATA_SAME();

    public String getERROR_MESSAGE_USER_GROUP_CREATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_IDENTITY_PROVIDER_CREATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_GROUP_UPDATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_USER_USER_GROUP_MAPPING_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_APPLICATION_USER_GROUP_MAPPING_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_CONTACT_ONBOARD_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_CONTACT_EDIT_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_MAPPER_CREATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_MAPPER_NOT_FOUND();

    public String getERROR_MESSAGE_SRA_DETAILS_NOT_MATCHED();

    public String getERROR_MESSAGE_INVALID_FILE_NAME();

    public String getERROR_MESSAGE_INPROGRESS();

    public String getERROR_MESSAGE_ENTERPRISE_ALREADY_ONBOARDED();

    public String getERROR_MESSAGE_NOTIFICATION_TYPE_NOT_FOUND();

    public String getERROR_MESSAGE_TWO_FACTOR_AUTH_DISABLED_FOR_USER();

    public String getERROR_MESSAGE_TWO_FACTOR_AUTH_DISABLED_FOR_APPLICATION();

    public String getERROR_MESSAGE_INVALID_CONNECTION_SETTINGS();

    public String getERROR_MESSAGE_ADFS_DETAIL_NOT_FOUND();

    public String getERROR_MESSAGE_AD_DETAIL_NOT_FOUND();

    public String getERROR_MESSAGE_SAME_MAKER_REQUEST_APPROVED();

    public String getERROR_MESSAGE_INVALID_USERID_PASSWORD();

    public String getERROR_MESSAGE_INVALID_TYPE();

    public String getERROR_MESSAGE_PARSING_CSV();

    public String getERROR_MESSAGE_REQUEST_NOT_PENDING();

    public String getERROR_MESSAGE_ATTRIBUTE_MASTER_ADDITION_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ATTRIBUTE_META_DATA_NOT_FOUND();

    public String getERROR_MESSAGE_VERIFIER_NOT_FOUND();

    public String getERROR_MESSAGE_EVIDENCE_REQUEST_ALREADY_APPROVED();

    public String getERROR_MESSAGE_USER_GROUP_DELETE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ATTRIBUTE_NOT_PRESENT();

    public String getERROR_MESSAGE_INTERNAL_SERVER_ERROR();

    public String getERROR_MESSAGE_USER_BINDING_ALREDY_PRESENT();

    public String getERROR_MESSAGE_INVALID_DATA_OTP();

    public String getERROR_DEV_MESSAGE_INVALID_DATA();

    public String getERROR_DEV_MESSAGE_INVALID_TRANSACTION_ID();

    public String getERROR_DEV_MESSAGE_INVALID_SIGN_TRANSACTION_ID();

    public String getERROR_DEV_MESSAGE_INVALID_STATUS();

    public String getERROR_DEV_MESSAGE_INVALID_TOKEN();

    public String getERROR_MESSAGE_USER_PROVIDED_INVALID_CLIENT_ID_OR_SECRET();

    public String getERROR_MESSAGE_INVALID_ESC_FILE_NAME();

    public String getERROR_MESSAGE_INVALID_FILE_TYPE();

    public String getERROR_MESSAGE_ATTRIBUTE_PASSWORD();

    public String getERROR_MESSAGE_USER_PASSWORD();

    public String getERROR_MESSAGE_UPDATE_APPROVAL_ATTEMPT_FAILED();

    public String getERROR_MESSAGE_INVALID_VALUE();

    public String getERROR_MESSAGE_EMPTY_CSV();

    public String getERROR_MESSAGE_NOT_SUPPORTED();

    public String getERROR_MESSAGE_EVIDENCE_EXPORT_EVIDENCE_FAILED();

    public String getERROR_MESSAGE_EDIT_CREDENTIAL_FALIED();

    public String getERROR_MESSAGE_APPLICATION_ALREADY_BINDED();

    public String getERROR_MESSAGE_LICENSE_CHECK_FAILED_DUE_TO_EXPIRED_LICENSE();

    public String getERROR_MESSAGE_LICENSE_CHECK_FAILED_DUE_TO_APPLICATION_EXCEEDED();

    public String getERROR_MESSAGE_LICENSE_CHECK_FAILED_DUE_TO_USERS_EXCEEDED();

    public String getERROR_MESSAGE_ENTERPRISE_NOT_ONBOARDED();

    public String getERROR_MESSAGE_HOTP_GENERATION_FAILED();

    public String getERROR_MESSAGE_HOTP_VALIDATION_FAILED();

    public String getHUMANIZED_MESSAGE_AUTHENTICATION_FAILED();

    public String getHUMANIZED_AUTHENTICATION_FAILED();

    public String getHUMANIZED_GET_ADMIN_FAILED();

    public String getHUMANIZED_GET_USERS_FAILED();

    public String getHUMANIZED_GET_USER_STATUS_FAILED();

    public String getHUMANIZED_GET_SERVICES_FAILED();

    public String getHUMANIZED_GET_APPLICATION_FAILED();

    public String getHUMANIZED_GET_APPROVAL_ATTEMPT_FAILED();

    public String getHUMANIZED_USER_UDATE_FAILED();

    public String getHUMANIZED_USER_ONBOARD_FAILED();

    public String getHUMANIZED_CHANGE_PASSWORD_FAILED();

    public String getHUMANIZED_POLICY_ONBOARD_FAILED();

    public String getHUMANIZED_CONTACT_ONBOARD_FAILED();

    public String getHUMANIZED_GET_POLICY_FAILED();

    public String getHUMANIZED_GET_CONTACT_FAILED();

    public String getHUMANIZED_POLICY_EDIT_FAILED();

    public String getHUMANIZED_CONTACT_EDIT_FAILED();

    public String getHUMANIZED_USER_APPROVAL_FAILED();

    public String getHUMANIZED_USER_BINDING_FAILED();

    public String getHUMANIZED_USER_UNBINDING_FAILED();

    public String getHUMANIZED_FILE_UPLOAD_FAILED();

    public String getHUMANIZED_APPLICATION_SECRET_FAILED();

    public String getHUMANIZED_GET_DECRYPTION_FAILED();

    public String getHUMANIZED_APPROVAL_ATTEMPT_UPDATE_FAILED();

    public String getHUMANIZED_APPROVAL_ATTEMPT_CREATION_FAILED();

    public String getHUMANIZED_APPLICATION_DELETION_FAILED();

    public String getHUMANIZED_GET_USER_SUBSCRIPTION();

    public String getHUMANIZED_UNBIND_SERVICES();

    public String getHUMANIZED_BIND_SERVICES();

    public String getHUMANIZED_ERROR_AUDIT_TRAIL();

    public String getHUMANIZED_ERROR_VALIDATE_PASSWORD();

    public String getHUMANIZED_LOGOUT_FAILED();

    public String getHUMANIZED_REQUEST_APPROVAL_FAILED();

    public String getHUMANIZED_GET_REQUEST_FAILED();

    public String getHUMANIZED_VERIFICATION_FAILED();

    public String getHUMANIZED_ATTRIBUTE_ADDITION_FAILED();

    public String getHUMANIZED_GET_ATTRIBUTE_FAILED();

    public String getHUMANIZED_GET_CONFIG_FAILED();

    public String getHUMANIZED_UPLOAD_ATTRIBUTE_REQUEST();

    public String getHUMANIZED_GET_ATTRIBUTE();

    public String getHUMANIZED_REQUEST_ATTRIBUTE();

    public String getHUMANIZED_GET_EVIDENCE_STATUS();

    public String getHUMANIZED_APPROVE_EVIDENCE_REQUEST();

    public String getHUMANIZED_EVIDENCE_REQUEST();

    public String getHUMANIZED_GET_ENTERPRISE();

    public String getHUMANIZED_GET_VERIFIERS();

    public String getHUMANIZED_GET_ATTRIBUTE_REQUEST();

    public String getHUMANIZED_ONBOARD_APPLICATION();

    public String getHUMANIZED_EDIT_APPLICATION();

    public String getHUMANIZED_DELETE_APPLICATION();

    public String getHUMANIZED_ADD_TUNNEL_LOG();

    public String getHUMANIZED_GET_REMOTE_SETTINGS();

    public String getHUMANIZED_CSV_DOWNLOAD_FAILED();

    public String getHUMANIZED_GET_SRA_GATEWAY_SETTING();

    public String getHUMANIZED_ADD_SRA_GATEWAY_SETTING();

    public String getHUMANIZED_DELETE_SRA_GATEWAY_SETTING();

    public String getHUMANIZED_GET_DEVICES_FAILED();

    public String getHUMANIZED_GET_TOKENS_FAILED();

    public String getHUMANIZED_GET_DEVICE_TOKENS_FAILED();

    public String getHUMANIZED_EDIT_DEVICE_FAILED();

    public String getHUMANIZED_EDIT_TOKEN_FAILED();

    public String getHUMANIZED_USER_GROUP_ALREADY_EXISTS();

    public String getHUMANIZED_CREATE_USER_GROUP();

    public String getHUMANIZED_GET_USERGROUP_FAILED();

    public String getHUMANIZED_UPDATE_USER_GROUP();

    public String getHUMANIZED_USER_USER_GROUP_MAPPING();

    public String getHUMANIZED_USER_GROUP_BINDING_ALREADY_EXISTS();

    public String getHUMANIZED_USER_GROUP_BINDING_NOT_FOUND();

    public String getHUMANIZED_USER_GROUP_APPLICATION_BINDING_ALREADY_EXISTS();

    public String getHUMANIZED_USER_GROUP_APPLICATION_BINDING_NOT_FOUND();

    public String getHUMANIZED_USER_GROUP_APPLICATION_MAPPING();

    public String getHUMANIZED_GET_USERGROUP_APPLICATION_FAILED();

    public String getHUMANIZED_REMOVE_USER_GROUP();

    public String getHUMANIZED_EDIT_ATTRIBUTE_FAILED();

    public String getHUMANIZED_DELETE_ATTRIBUTE_FAILED();

    public String getHUMANIZED_QR_CODE_GENERATION_FAILED();

    public String getHUMANIZED_LOGS_DOWNLOAD_FAILED();

    public String getHUMANIZED_ONBOARD_ENTERPRISE_FAILED();

    public String getHUMANIZED_GET_STATE_MACHINE_WORKFLOW_FAILED();

    public String getHUMANIZED_GET_ACCOUNT_CUSTOM_STATE_MACHINE_FAILED();

    public String getHUMANIZED_STATE_MACHINE_WORKFLOW_ONBOARD_FAILED();

    public String getHUMANIZED_STATE_MACHINE_WORKFLOW_EDIT_FAILED();

    public String getHUMANIZED_GET_ATTEMPT_TYPES_FAILED();

    public String getHUMANIZED_GET_CHALLENGE_TYPES_FAILED();

    public String getHUMANIZED_ACCOUNT_CUSTOM_STATE_MACHINE_ONBOARD_FAILED();

    public String getHUMANIZED_ACCOUNT_CUSTOM_STATE_MACHINE_EDIT_FAILED();

    public String getERROR_MESSAGE_USER_CREDENTIALS_NOT_PRESENT();

    public String getERROR_MESSAGE_EVIDENCE_IS_REQUIRED();

    public String getERROR_MESSAGE_INVALID_BULK_UPLOAD_TYPE();

    public String getHUMANIZED_UPLOAD_FAILED();

    public String getHUMANIZED_DOWNLOAD_STATUS_FILE_FAILED();

    public String getHUMANIZED_DOWNLOAD_SAMPLE_CSV_FILE_FAILED();

    public String getERROR_MESSAGE_APPLICATION_NOT_ACTIVE();

    public String getHUMANIZED_FETCH_QR_STATUS_FAILED();

    public String getERROR_MESSAGE_INVALID_SERACH_ATTRIBUTE();

    public String getERROR_MESSAGE_DUPLICATE_SEARCH_ATTRIBUTE();

    public String getERROR_MESSAGE_DUPLICATE_ATTRIBUTE();

    public String getERROR_MESSAGE_INVALID_ACCOUNT_ID();

    public String getERROR_MESSAGE_APPLICATION_NOT_FOUND();

    public String getERROR_MESSAGE_APPLICATION_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ATTRIBUTE_ALREADY_PRESENT_TO_OTHER();

    public String getERROR_MESSAGE_USER_UPDATE_PENDING();

    public String getERROR_MESSAGE_INVALID_TOKEN();

    public String getERROR_MESSAGE_PERMISSION_DENIED();

    public String getERROR_MESSAGE_IO_EXCEPTION();

    public String getERROR_MESSAGE_INVALID_APPLICATION_ID_OR_PASSWORD();

    public String getERROR_MESSAGE_USER_SERVICE_BINDING_FAILED();

    public String getERROR_MESSAGE_INVALID_MOBILE();

    public String getERROR_MESSAGE_INVALID_APPLICATION_FOR_USER();

    public String getERROR_MESSAGE_SERVER_ERROR();

    public String getERROR_MESSAGE_ACCOUNT_NOT_FOUND();

    public String getERROR_MESSAGE_LOOKUP_ID_COMPULSORY();

    public String getERROR_MESSAGE_APPROVAL_ATTEMPT_TYPE_INVALID();

    public String getERROR_MESSAGE_INVALID_CONSUMER_ID();

    public String getERROR_MESSAGE_APPROVAL_ATTEMPT_NOT_APPROVED();

    public String getERROR_MESSAGE_INVALID_APPLICATION_ID();

    public String getERROR_MESSAGE_INVALID_ADMIN_ROLE();

    public String getERROR_MESSAGE_STATE_MACHINE_WORKFLOW_ONBOARD_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_STATE_MACHINE_WORKFLOW_UPDATE_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ACCOUNT_CUSTOM_STATE_MACHINE_ONBOARD_REQUEST_ALREADY_PRESENT();

    public String getERROR_MESSAGE_ACCOUNT_CUSTOM_STATE_MACHINE_UPDATE_REQUEST_ALREADY_PRESENT();
   public String  getERROR_MESSAGE_ATTRIBUTE_UPDATE_REQUEST_ALREADY_PRESENT1();
   public Long getERROR_CODE_INVALID_SERACH_ATTRIBUTE();
   public String getUPDATE_PASSWORD_FAILED();
   public String getERROR_MESSAGE_SAME_PASSWORD();
    public long getERROR_CODE_INVALID_PASSWORD();
    public long getERROR_CODE_FALLOUT_INVALID_DATA();
    public String getERROR_MESSAGE_FALLOUT_INVALID_DATA();
    public String getERROR_MESSAGE_CONSENT_REQUIRED_NOT_ALLOWED();
    public long getERROR_CODE_CONSENT_REQUIRED_NOT_ALLOWED();
    public String getHUMANIZED_CHANGE_ENTERPRISE_PIN_FAILED();
    public String getHUMANIZED_CHANGE_APPLICATION_PIN_FAILED();
    public String getHUMANIZED_RESET_APPLICATION_PIN_FAILED();
    public String getERROR_MESSAGE_INVALID_FALLOUT_OPERATION();
    public long getERROR_CODE_INVALID_FALLOUT_OPERATION();
    public String getHUMANIZED_RESET_ENTERPRISE_PIN_FAILED();
    public long getERROR_CODE_INVALID_SEARCH_ATTRIBUTE();
    public String getACCOUNT_POLICY_FAILED();
    public String getHUMANIZED_GENERATE_RUNNING_HASH_FAILED();
    public String getHUMANIZED_VERIFY_RUNNING_HASH_FAILED();
    public String getERROR_MESSAGE_INVALID_RUNNING_HASH();
    public long getERROR_CODE_THEME_NOT_FOUND();
    public String getERROR_MESSAGE_THEME_NOT_FOUND();


    public Long  getERROR_CODE_MULTIPLE_IDENTITIES_FOUND();
    public String getERROR_MESSAGE_MULTIPLE_IDENTITIES_FOUND();


    String getERROR_MESSAGE_USER_NAME_TOKEN_INVALID();

    String getERROR_MESSAGE_INVALID_USER_CREDENTIALS();

    String getERROR_MESSAGE_DISABLE_USER_FAILED();

    long getERROR_CODE_DISABLE_USER_ALREADY_PRESENT();

    String getERROR_MESSAGE_DISABLE_USER_ALREADY_PRESENT();

    long getERROR_CODE_USER_LOGIN_TIME_EXPIRED();

    String getERROR_MESSAGE_USER_LOGIN_TIME_EXPIRED();
     String getERROR_MESSAGE_INVALID_USER_STATE();

    String getHUMANIZED_EDIT_FALLOUT_CONFIG();

    String getERROR_MESSAGE_EDIT_FALLOUT_CONFIG_ALREADY_PRESENT();

    Long getERROR_CODE_EDIT_FALLOUT_CONFIG_ALREADY_PRESENT();

    String getERROR_MESSAGE_UPDATE_FALLOUTSYNCDATA_ALREADY_PRESENT();

    String getERROR_MESSAGE_FALLOUT_SYNC_DATA_NOT_FOUND();

    String getHUMANIZED_ADD_CONFIG();

    String getERROR_MESSAGE_ADD_CONFIG_ALREADY_PRESENT();

    String getHUMANIZED_UPDATE_CONFIG();

    String getERROR_MESSAGE_UPDATE_CONFIG_ALREADY_PRESENT();

    Long getERROR_CODE_CONFIG_NOT_FOUND();

    String getERROR_MESSAGE_CONFIG_NOT_FOUND();

    Long getERROR_CODE_CONFIG_ALREADY_PRESENT();

    String getERROR_MESSAGE_CONFIG_ALREADY_PRESENT();
    String getERROR_DEV_MESSAGE_INVALID_REQUEST_BODY();

    String getERROR_MESSAGE_LDAP_DETAILS_EDIT_REQUEST_ALREADY_PRESENT();

    String getERROR_MESSAGE_LDAP_DETAILS_ADD_REQUEST_ALREADY_PRESENT();

    String getERROR_MESSAGE_LDAP_DETAILS_EDIT_REQUEST_FAILED();

    String getERROR_MESSAGE_LDAP_DETAILS_ADD_REQUEST_FAILED();

    String getERROR_MESSAGE_GET_LDAP_FAILED();

    String getERROR_MESSAGE_LDAP_DETAILS_ALREADY_PRESENT();

    String getERROR_MESSAGE_SELF_BLOCKING_NON_PERMITTED();

    String getERROR_MESSAGE_CREATE_TEMP_DETAILS_REQUEST_ALREADY_PRESENT();

    String getERROR_MESSAGE_EDIT_TEMP_DETAILS_REQUEST_ALREADY_PRESENT();

    String getERROR_MESSAGE_CREATE_TEMP_DETAILS_FAILED();

    String getERROR_MESSAGE_GET_TEMP_DETAILS_REQUEST_FAILED();

    public String getERROR_MESSAGE_DELETE_TEMP_DETAILS_REQUEST_FAILED();

    public String getERROR_MESSAGE_DELETE_TEMP_DETAILS_REQUEST_ALREADY_PRESENT();

    String getERROR_MESSAGE_TEMP_NAME_ALREADY_PRESENT();

    String getERROR_MESSAGE_UPDATE_TEMP_DETAILS_REQUEST_FAILED();

    String getERROR_MESSAGE_INVALID_TEMPLATE_FOR_APPLICATION();

    String getERROR_MESSAGE_VALIDATION_RULE_ALREADY_EXIST();

    Long getERROR_CODE_TEMPLATE_NOT_FOUND();

    String getERROR_MESSAGE_TEMPLATE_NOT_FOUND();
}
    

