package in.fortytwo42.adapter.enums;

public enum ActionName {
	USER_REQUEST_INITIATED, 
	USER_REQUEST_APPROVAL, 
	APPLICATION_REQUEST_INITIATED, 
	APPLICATION_REQUEST_APPROVAL, 
	USER_2FA_ENABLED;
}
