
package in.fortytwo42.adapter.enums;

public enum PasswordPolicyRuleType {

    MORE_THAN_THREE_CONSECUTIVE_REPEATTING_DIGITS,
    FOUR_OR_MORE_SEQUENCED_DIGITS,
    TWO_DIGIT_REPEATING_SEQUENCE,
    THREE_DIGIT_REPEATING_SEQUENECE,
    THREE_DIGIT_SEQUENCE_REPEATING,
    PASS_HISTORY

}
